### PR TITLE
add ServiceKind and DisplayAspectRatio_Original

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by ablwr** [comment]
interesting

**Comment by dericed** [comment]
found DisplayAspectRatio_Original was used by not in the schema as well

**Comment by dericed** [comment]
@ablwr IIUC `Service Kind` is a clarifier for AC-3 audio

**Comment by dericed** [comment]
added one more, based on testing, but done for now. plz review

**Comment by dericed** [comment]
ping

**Pull request merged**
